Origin-Byte/nft-protocol

- Move.toml
- README.md
- sources/launchpad/market/fixed_price.move
The toggling of the sale status of a launchpad should be exclusive to its admin and not accessible to any person.
> Toggling Sale Status Permissions

- CHANGELOG.md
- Move.toml
- sources/launchpad/sale.move
- sources/launchpad/slingshot.move
- sources/nft/nfts/unique_nft.move
- Updated Sui dep to `0.14.0`
- Since `transfer_to_object` was deprecated, we now use `dynamic_object_field`
with slingshot to associate embedded NFTs.
> Upgrading to Sui 0.14.0

- Cargo.lock
- gutenberg/Cargo.toml
- gutenberg/examples/collectibles.yaml
- gutenberg/src/lib.rs
- gutenberg/src/main.rs
- gutenberg/src/schema.rs
- gutenberg/tests/generate.rs
- sources/examples/collectibles.move
- sources/examples/multi_sales.move
Allows `Schema::write_move` to take a generic parameter, allowing us to write basic integration tests that check `gutenberg` generation. 
Would like to use this for testing generated auction code.
> Gutenberg integration tests

- Cargo.lock
- gutenberg/Cargo.toml
- gutenberg/src/err.rs
- gutenberg/src/main.rs
- gutenberg/src/schema.rs
- gutenberg/src/types.rs
- gutenberg/tests/generate.rs
- sources/examples/multi_sales.move
- Uses `serde-derive` to automatically deserialize `Schema`.
- Validates that schema for all our examples is correct.
Rebased on top of https://github.com/Origin-Byte/nft-protocol/pull/60
> Serde derive

- Cargo.lock
- gutenberg/Cargo.toml
- gutenberg/src/err.rs
- gutenberg/src/main.rs
- gutenberg/src/prelude.rs
- gutenberg/src/schema.rs
- gutenberg/src/types.rs
- Cleans up `GutenError` cases
- Cleans up `prelude`, which should be used to export crate types not std types
> Cleanup errors and prelude

- sources/safe/safe.move
- sources/utils/err.move
- tests/safe.move
```
aldrin@porkbrain:~/Code/nft-protocol(tests/safe)$ sui move coverage summary
+-------------------------+
| Move Coverage Summary   |
+-------------------------+
Module 0000000000000000000000000000000000000000::err
>>> % Module coverage: 18.60
Module 0000000000000000000000000000000000000000::utils
>>> % Module coverage: 75.86
Module 0000000000000000000000000000000000000000::tags
>>> % Module coverage: 31.25
Module 0000000000000000000000000000000000000000::supply
>>> % Module coverage: 3.21
Module 0000000000000000000000000000000000000000::supply_policy
>>> % Module coverage: 5.00
Module 0000000000000000000000000000000000000000::domain
>>> % Module coverage: 0.00
Module 0000000000000000000000000000000000000000::collection
>>> % Module coverage: 34.98
Module …
```
> Tests: Safe module

- examples/whitelisting/free_for_all.move
- sources/collection/collection.move
- sources/safe/transfer_whitelist.move
- tests/transfer_whitelist.move
```
Test result: OK. Total tests: 41; passed: 41; failed: 0
+-------------------------+
| Move Coverage Summary   |
+-------------------------+
Module 0000000000000000000000000000000000000000::err
>>> % Module coverage: 23.26
Module 0000000000000000000000000000000000000000::utils
>>> % Module coverage: 75.86
Module 0000000000000000000000000000000000000000::tags
>>> % Module coverage: 31.25
Module 0000000000000000000000000000000000000000::supply
>>> % Module coverage: 3.21
Module 0000000000000000000000000000000000000000::supply_policy
>>> % Module coverage: 5.00
Module 0000000000000000000000000000000000000000::domain
>>> % Module coverage: 0.00
Module 0000000000000000000000000000000000000000::collection
>>> % Module coverage: 37.34
Module …
```
> Tests: trading whitelist

- examples/suimarines.move
- examples/suitraders.move
- sources/standards/attribution.move
- sources/standards/royalties/royalty.move
Makes `RoyaltyDomain` more ergonomic to work around by only asserting that `ctx` is a creator when obtaining a mutable reference from `Collection`.
Rebased on top of https://github.com/Origin-Byte/nft-protocol/pull/127
> Feature: Permissionless royalty domain

- sources/launchpad/launchpad.move
- sources/nft/nft.move
- sources/safe/safe.move
- sources/safe/unprotected_safe.move
- sources/standards/display.move
- sources/standards/tags.move
- tests/safe.move
Struct names in capital letters, equal to the name of their module, are reserved to [One-Time Witnesses](https://examples.sui.io/basics/one-time-witness.html).
> Fix: Rename NFT to Nft

- sources/safe/safe.move
- sources/trading/bidding.move
- tests/safe.move
The default behavior is that anyone can deposit NFTs into a safe. Optionally, one can call the `restrict_deposits` method to configure the safe.
Why default to true? It's the more common use case for trading and games, making it simpler for usage. The devs need to be aware of how safe works anyway, plus we've got docs, so this isn't a security vuln imho.
> Removing the argument for enabling any deposit when creating a new Safe

- sources/launchpad/inventory.move
- sources/launchpad/market/dutch_auction.move
- sources/launchpad/market/fixed_price.move
- sources/launchpad/proceeds.move
- sources/launchpad/slot.move
- tests/market/dutch_auction.move
- tests/market/fixed_price.move
- tests/slot.move
Adds dutch auction market tests
- Rearranged tests in fixed price market
- Changed wallet API in both markets
- Removed `Proceeds.total` due to potentially adding up different `FT`s, we can reintroduce it in a follow-up MR
> Feature: Dutch auction market tests

- .gitignore
- examples/suimarines.move
- examples/suitraders.move
- sources/launchpad/inventory.move
- sources/launchpad/market/dutch_auction.move
- sources/launchpad/market/fixed_price.move
- sources/launchpad/slot.move
- tests/market/dutch_auction.move
- tests/market/fixed_price.move
- tests/mint_and_sell.move
The intial purpose of NftCertificate was to allow the Launchpad to emit a certificate with an NFT ID, such that the user could then use this Certificate in a second function call to redeem the NFT with that ID. This had to be done because there were no Dynamic Fields before. Now, with the introduction of dynamic fields this two step process can be simplified to one step, and as a result, it improves the UX of the Marketplaces.
> Feature: Remove NFT Certificate

- CHANGELOG.md
- examples/football.move
- examples/suimarines.move
- examples/suitraders.move
- sources/launchpad/inventory.move
- sources/launchpad/market/dutch_auction.move
- sources/launchpad/market/fixed_price.move
- sources/nft/nft.move
- sources/standards/creators.move
- sources/standards/display.move
- sources/standards/royalties/royalty.move
- sources/standards/royalties/royalty_strategy.move
- sources/standards/tags.move
- sources/trading/bidding.move
- sources/trading/ob.move
- sources/utils/err.move
- tests/bidding/safe_to_safe_trade.move
- tests/domains/royalty.move
- tests/mint_and_sell.move
Refactors RoyaltyDomain and CreatorsDomain to split royalty share and authorization logic.
- Documents both domains in their new form
- Accessibility improvements in creating RoyaltyDomain
- Allow NFTs to be withdrawn from Inventory to an address without going through launchpad
> RoyaltyDomain refactor

- CHANGELOG.md
- sources/safe/royalties.move
- sources/safe/unprotected_safe.move
- sources/trading/ob.move
- tests/utils.move
- Orderbook event `AskCreatedEvent`/`BidCreatedEvent` are emitted when
creating a new position in orderbook.
- Orderbook event `AskClosedEvent`/`BidClosedEvent` are emitted when
closing a position in orderbook.
- Orderbook event `TradeFilledEvent` is emitted when a trade is filled.
That is, either on `create_bid`/`create_ask` when the trade is immediately
filled, or on `buy_nft`/`buy_generic_nft`.
- Royalties event when `TradePayment` is created.
- When creating a bid higher than the lowest ask, the bid is now filled with
the lowest ask price.
Before, it was filled with the bid price.
> Emitting events in orderbook

- CHANGELOG.md
- Move.toml
- sources/trading/ob.move
- sources/utils/err.move
- tests/ob/safe_to_safe_trade.move
- In orderbook, it was possible to create an ask or a bid which would require
that the `finish_trade` function be called with buyer and seller safe as the
same object.
This is not possible anymore as such tx would result in an error.
---
Closes #227
> Fixed problem with trading in within the same safe

- CHANGELOG.md
- Move.toml
- sources/trading/ob.move
- Orderbook's `TradeFilledEvent` now contains orderbook ID.
> Feature: orderbook trade filled event has orderbook ID

- CHANGELOG.md
- Move.toml
- sources/collection/collection.move
- sources/standards/royalties/royalty.move
- sources/standards/tags.move
- `TagsDomain` now uses dynamic fields instead of `Bag`.
- `RoyaltyDomain` now uses dynamic fields instead of `Bag`.
> We no longer use Bag because it's RPC unfriendly

- CHANGELOG.md
- sources/trading/orderbook.move
- tests/orderbook/commission.move
- tests/orderbook/trade.move
- `orderbook::list_nft` and `orderbook::list_nft_with_commission` endpoints.
These allow the client to skip the creation of transfer caps and instead
provide `OwnerCap` to `Safe` directly to the orderbook contract.
> Listing NFTs in orderbook creates a transfer cap

- examples/footbytes.move
- examples/suimarines.move
- examples/suitraders.move
- sources/nft/nft.move
- Cleanup redundant witness check on `nft::add_domain_with_mint_cap`
- No reason that `MintCap` owner should be allowed to register arbitrary domains on existing NFTs that it does not own using `nft::add_domain_with_mint_cap`, removed that ability.
> Chore: MintCap issues

- CHANGELOG.md
- sources/trading/orderbook.move
A discussion with a marketplace about putting actions into one txs. Here's my response:
> I am wondering how to organize these helper functions.
>
> One option is to have marketplace smart contract into which we can push them. The pro is that you don't rely on OB release cycle which is important going forward. The disadvantage is overhead of setting this up and maintenance.
> The second option is to have this in the OB contract. The advantage is that it's all in one place and other marketplaces or clients can take advantage too. The disadvantage is that at some point we have to release NFT protocol and that's that, no more helper functions.
> A third option is an extension contract maintained by OB where we would publish logic that can viably change but we wouldn't want to update the core …
> Orderbook endpoints which minimise txs

- CHANGELOG.md
- sources/trading/orderbook.move
The marketplaces can now `cancel_ask_and_discard_transfer_cap`
> Endpoint to cancel ask and discard the transfer cap in a single tx

- CHANGELOG.md
- sources/trading/orderbook.move
- sources/utils/err.move
- tests/orderbook/cancel_position.move
- tests/orderbook/commission.move
- tests/orderbook/safe_to_safe_trade.move
- tests/orderbook/trade.move
- tests/orderbook/witness_protected_actions.move
- Helper endpoints in orderbook which allow marketplaces to perform actions in a single tx.
The marketplaces can now
- `list_multiple_nfts`
- Moved errors from `err` module into `orderbook` module where they are expressed as constants.
> Endpoint to list multiple NFTs in one tx

- CHANGELOG.md
- sources/nft/nft.move
- sources/trading/orderbook.move
- sources/utils/err.move
- tests/orderbook/cancel_position.move
- tests/orderbook/commission.move
- tests/orderbook/safe_to_safe_trade.move
- tests/orderbook/trade.move
- tests/orderbook/witness_protected_actions.move
- Helper endpoints in orderbook which allow marketplaces to perform actions in a single tx.
The marketplaces can now
- `edit_bid`
- `create_safe_and_bid`
- `create_safe_and_bid_with_commission`
- Wrong `seller` field in `TradeFilledEvent` when calling the `buy_nft` endpoint
> Bid ergonomics

- examples/footbytes.move
- examples/free_for_all.move
- examples/suimarines.move
- examples/suitraders.move
- examples/symbol.move
- sources/collection/collection.move
- sources/nft/nft.move
- sources/standards/display.move
- sources/standards/loose/templates.move
- sources/standards/modify.move
- sources/standards/plugins.move
- sources/standards/royalties/royalty.move
- sources/standards/supply.move
- sources/standards/tags.move
- tests/bidding/safe_to_safe_trade.move
- tests/domains/creators.move
- tests/domains/display.move
- tests/domains/royalty.move
- tests/domains/tags.move
- tests/nft.move
Creates new `add_domain_delegated` and `add_domain` endpoints in order to provide a user-friendly endpoint for cases where the user does not need to understand what the delegated witness is.
> Example: Unique symbol domain

- CHANGELOG.md
- sources/trading/bidding.move
- sources/trading/trading.move
- `BidCreated` renamed to `BidCreatedEvent`, generic removed and new fields added.
The generic is problematic for the client as it can then query only for event type knowing the fungible token in advance.
- `BidClosed` event renamed to `BidClosedEvent`, again generic removed and new fields added.
Additionally, this event is now used only for cancelling a bid.
- `BidMatchedEvent` emitted when an NFT is sold.
> Ergonomics: bidding contract

- CHANGELOG.md
- sources/nft/nft.move
- sources/trading/bidding.move
- sources/trading/orderbook.move
- `OrderbookCreatedEvent` property `fungible_token_type` renamed to `ft_type` to be consistent with other events.
- `BidCreatedEvent`, `BidClosedEvent` and `BidMatchedEvent` property `ft` renamed to `ft_type` to be consistent with other events.
- `ChangeLogicalOwnerEvent` emitted when logical owner of an NFT is changed.
It contains old and new logical owner, NFT ID and NFT collection type.
- `OrderbookCreatedEvent` exported collection type instead of FT type.
> Event type exports

- examples/tribal_realms.move
- sources/standards/composability/composable_nft.move
- sources/standards/composability/nft_bag.move
The cNFT feature should have the following specifications:
1. Creators should be able to define different Nft types within their collections (e.g. `Avatar`, `Weapon`, `Hat`, etc.)
2. Creators should be able to define how NFTs from different types compose with each other:
- What is the maximum amount of numbers a NFT type can attach to another
- What is the redenring order of the pictures?
In relation to the rendering order there are essentially two ways in which we can render composable NFTs:
1- The rendering occurs dynamically and facilitated by the client who reads urls and stacks pictures on top of each other
2- The rendering of the stack images occurts preemptively and it is dynamically loaded to IPFS or any other storage service and compose time. (This later requires an off-chain …
> Feature: Composable NFTs

- examples/footbytes.move
- examples/simple.move
- examples/suimarines.move
- examples/suitraders.move
- examples/tribal_realms.move
- sources/standards/attributes.move
- sources/standards/composability/svg.move
- sources/standards/composability/url.move
- sources/standards/display.move
- sources/standards/url.move
- sources/utils/utils.move
- tests/domains/display.move
Alternative to https://github.com/Origin-Byte/nft-protocol/pull/243.
Composes `UrlDomain` and `AttributesDomain` into `Nft.url` for best display compatibility.
> Feature: Compose `Nft.url`

- examples/tribal_realms.move
- sources/standards/attributes.move
- sources/standards/composability/composable_nft.move
- sources/standards/composability/nft_bag.move
- sources/standards/composability/svg.move
* Bring `Composition` domain interface inline with others after rewrite
* Remove type restriction from `NFtBag`, this was needlessly strict and there is no situation where you don't know the type of the NFT you're withdrawing like Warehouse.
> Feature: Composability fixes

- examples/allowlists/free_for_all.move
- examples/simple.move
- examples/suimarines.move
- examples/suitraders.move
- examples/symbol.move
- examples/tribal_realms.move
- sources/collection/mint_cap.move
- tests/utils.move
Currently, the supply of a type is essentially unenforceable, because one can use the `Publisher` or the `DelegatedWitness` at any time to create new MintCaps.
The only way to guarantee that a supply is Capped is to therefore burn or lock the `Publisher`, which is too big of sacrifice, since `Publisher` is also used in the context of other frameworks, and also used on our protocol to get the delegated witness, which the creator needs to manage certain aspects of the collection.
Therefore the `MintCap` object should be at the same level as the `Publisher`, in that it should have to be claimed in the init function. To enforce this we just need to assert the following.
> Feature: Init MintCap via OTW 

- launchpad_v2/sources/venue.move
- sources/collection/mint_cap.move
- sources/collection/mint_pass.move
- sources/standards/mint_supply.move
- sources/standards/supply.move
- sources/utils/err.move
- sources/utils/supply.move
- sources/utils/utils.move
- Functionally equivalent to `GlobalSupply` but renamed to `MintSupply` which makes more sense in the context of centralizing control of `MintCap` delegation.
- Introduces a helper type `utils_supply::Supply` which is used across different modules
- `supply::Supply` now has functioning protection, currently it's endpoints are unprotected
- Unified `supply` structure and endpoints with rest of codebase
- Removes a bunch of old error definitions :)
> Feature: MintSupply

- contracts/liquidity_layer/Move.lock
- contracts/liquidity_layer/Move.toml
- contracts/liquidity_layer/sources/trading/orderbook.move
- contracts/tests/tests/liquidity_layer/orderbook/depth.move
- contracts/tests/tests/liquidity_layer/orderbook/orderbook.move
- contracts/tests/tests/utils.move
- example_collections/examples/sources/testract.move
- Removes `WitnessProtectedActions` from public API
- Introduces entry APIs all over the place
- Removes redundant computation on Orderbook by using index endpoints
- Use separately published `Critbit`
- Comprehensive initialization endpoints
> Feature: Orderbook entry
