Origin-Byte/nft-protocol

CHANGELOG.md
Move.toml

- https://diem.github.io/move/packages.html

Renaming Move package name to adhere to Move naming conventions

---

CHANGELOG.md
Move.toml
README.md
sources/launchpad/fixed_price.move
sources/nft/std_nft.move

Rename `uri` to `url` in `std_nft::NftMeta`
Permissioned launchpad creation in `fixed_price::create`

Rename uri to url & permissioned launchpad creation

---

sources/examples/suimarines.move

Example Suimarines NFT module

---

CHANGELOG.md
sources/examples/suimarines.move
sources/launchpad/market/fixed_price.move
sources/launchpad/sale.move
sources/launchpad/slingshot.move
sources/supply/policy.move

- `Slingshot` has now witness pattern for type exported NFT type

Launchpad Witness Pattern

---

CHANGELOG.md
sources/examples/suimarines.move
sources/nft/nfts/c_nft.move
sources/nft/nfts/collectibles.move
sources/nft/nfts/unique_nft.move

- Removed field `index` from `unique_nft::Unique`, `collectibles::Collectible` and `c_nft::Data`

Removed NFT index field

---

CHANGELOG.md
sources/collection/collection.move
sources/launchpad/market/fixed_price.move
sources/launchpad/sale.move
sources/launchpad/slingshot.move
sources/launchpad/whitelist.move
sources/nft/nft.move
sources/nft/nfts/c_nft.move
sources/nft/nfts/collectibles.move
sources/nft/nfts/unique_nft.move
sources/supply/policy.move
sources/supply/supply.move
sources/utils/err.move

Added error handling via `err` module

Error handling module

---

CHANGELOG.md
Move.toml
sources/collection/collection.move
sources/nft/nfts/c_nft.move
sources/nft/nfts/collectibles.move
sources/nft/nfts/unique_nft.move
sources/supply/policy.move
sources/supply/supply.move

Toggling Sale Status Permissions
Remove option from max supply field

Toggle sale status permissions + simplify max supply field

---

CHANGELOG.md
Move.toml
README.md

Updating Sui to 0.15.0

---

sources/safe/safe.move

Replacing `ObjectBag` that stored NFTs in `Safe` with dynamic object fields.

Using dof instead of object bag for NFT storage

---

examples/suimarines.move
examples/suitraders.move
sources/collection/collection.move
sources/standards/attribution.move
sources/standards/display.move
sources/standards/royalties/royalty.move
sources/standards/tags.move

- Cleans up Collection a bit
- Mutable API for display standards
- Mutable API for TagDomain
- Interoperability API for AttributionDomain

Feature: Mutable API for Collection domains 

---

sources/launchpad/fees/flat_fee.move
sources/launchpad/market/dutch_auction.move

Removes more ObjectBox exposure in public API

Fix: Remove more ObjectBox

---

sources/standards/royalties/royalty.move

Allows users to more easily register their own royalty policies

Feature: Generic royalty domain

---

sources/launchpad/launchpad.move
sources/launchpad/market/dutch_auction.move
sources/launchpad/market/fixed_price.move

Cannot get mutable reference to dynamic fields of object

Fix: Use indirect market reference

---

examples/suimarines.move
examples/suitraders.move
sources/launchpad/fees/flat_fee.move
sources/launchpad/inventory.move
sources/launchpad/launchpad.move
sources/launchpad/market/dutch_auction.move
sources/launchpad/market/fixed_price.move
sources/launchpad/slot.move
sources/launchpad/whitelist.move

Much easier to reason about the logic that each component is responsible for and integrate future functionality such as Whitelists.

Chore: Separate Launchpad and Slot

---

examples/whitelisting/free_for_all.move
sources/collection/collection.move
sources/launchpad/inventory.move
sources/launchpad/launchpad.move
sources/launchpad/market/dutch_auction.move
sources/launchpad/market/fixed_price.move
sources/launchpad/proceeds.move
sources/launchpad/slot.move
sources/nft/nft.move
sources/safe/royalties.move
sources/safe/safe.move
sources/safe/transfer_whitelist.move
sources/safe/unprotected_safe.move
sources/standards/attribution.move
sources/standards/display.move
sources/standards/flyweight.move
sources/standards/royalties/royalty.move
sources/standards/tags.move
sources/supply/policy.move
sources/supply/supply.move
sources/trading/bidding.move
sources/trading/ob.move
sources/trading/trading.move
sources/utils/err.move
sources/utils/utils.move
tests/bidding/safe_to_safe_trade.move
tests/ob/safe_to_safe_trade.move

Chore: Module docs

---

CHANGELOG.md
examples/suitraders.move
sources/launchpad/inventory.move
sources/launchpad/market/dutch_auction.move
sources/launchpad/market/fixed_price.move
sources/launchpad/slot.move
sources/utils/err.move
tests/market/dutch_auction.move
tests/market/fixed_price.move
tests/mint_and_sell.move

Registers Markets on Inventory allowing users to sell one Inventory through different sales channels.

Feature: Register markets on Inventory

---

CHANGELOG.md
examples/suitraders.move
sources/launchpad/inventory.move
sources/launchpad/market/dutch_auction.move
sources/launchpad/market/fixed_price.move
sources/launchpad/slot.move
tests/market/dutch_auction.move
tests/market/fixed_price.move
tests/mint_and_sell.move

Feature: Live tracking

---

.github/workflows/sui-publish.yml
.github/workflows/sui-test.yml

Do not allow commiting with published address unless its a publish commit

Chore: Redo workflow

---

rfc/003-display-standards.md

Updated README

---

Move.toml
examples/football.move
examples/suimarines.move
examples/suitraders.move
sources/collection/collection.move
sources/nft/nft.move
sources/standards/creators.move
sources/standards/display.move
sources/standards/royalties/royalty.move
sources/standards/supply.move
sources/standards/tags.move
tests/domains/creators.move
tests/domains/display.move
tests/mint_and_sell.move
tests/nft.move

Feature: ObjectBag NFT

---

CHANGELOG.md
Move.toml
sources/trading/ob.move

- Orderbook's `CreateAskEvent` and `CreateBidEvent` now contain safe ID.
- Emitting event `OrderbookCreatedEvent` when an orderbook is created.

Improving orderbook events

---

CHANGELOG.md
sources/trading/orderbook.move
tests/orderbook/commission.move
tests/orderbook/safe_to_safe_trade.move

- Orderbook recipient was wrong when trading in orderbook.
---
Closes #241

Fix: orderbook recipient

---

sources/kiosk/ob_kiosk.move
sources/standards/transfer_allowlist/transfer_allowlist.move
sources/utils/utils.move

- New object `OwnerToken` which is helpful for off chain discovery
- Docs for `ob_kiosk`
- Display standard for `OwnerToken` and `TransferAllowlist`

Kiosk OwnerToken and Display

---

contracts/kiosk/sources/kiosk/ob_kiosk.move
contracts/tests/tests/kiosks/ob_kiosk.move

- Fully documented most functions, some function locations are re-arranged
- Improved error reporting throughout
- Quality of life improvements to working with locked NFTs

Feature:  Kiosk improvements

---

contracts/launchpad/sources/launchpad/market/dutch_auction.move
contracts/launchpad/tests/market/dutch_auction.move

Closes https://github.com/Origin-Byte/nft-protocol/issues/490

Fix: Dutch auction kiosk
